name: Slack Comment Notifier

on:
  issue_comment:
  pull_request_review_comment:

jobs:
  notify-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Send Comment to Slack
        if: github.event.action == 'created'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            ${{ toJSON({
              text: ":speech_balloon: *" + github.actor + "* commented:\n>" + github.event.comment.body + "\n\n🔗 <" + github.event.comment.html_url + "|코멘트 바로 가기>"
            }) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
